CCFLAGS = -Wextra -Werror -Wall

RESET = \033[0;39m
GRAY = \033[0;90m
RED = \033[0;91m
GREEN = \033[0;92m
YELLOW = \033[0;93m
BLUE = \033[0;94m
MAGENTA = \033[0;95m
CYAN = \033[0;96m
WHITE = \033[0;97m

# LEVEL 1

first_word:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

fizzbuzz:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

ft_putstr:
	@echo "$(YELLOW)Warning: $(RED)$@ $(RESET)is a function."
	@echo "$(YELLOW)Warning: $(RED)Nothing Compiled !$(RESET)"

ft_strcpy:
	@echo "$(YELLOW)Warning: $(RED)$@ $(RESET)is a function."
	@echo "$(YELLOW)Warning: $(RED)Nothing Compiled !$(RESET)"

ft_strlen:
	@echo "$(YELLOW)Warning: $(RED)$@ $(RESET)is a function."
	@echo "$(YELLOW)Warning: $(RED)Nothing Compiled !$(RESET)"

ft_swap:
	@echo "$(YELLOW)Warning: $(RED)$@ $(RESET)is a function."
	@echo "$(YELLOW)Warning: $(RED)Nothing Compiled !$(RESET)"

repeat_alpha:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

rev_print:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

rot_13:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

rotone:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

search_and_replace:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

ulstr:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

# LEVEL 2

alpha_mirror:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

camel_to_snake:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

do_op:
	@gcc $(CCFLAGS) $@/$@.c -o _outputs/$@
	@echo "$(GREEN)$@ compiled in $(BLUE)_outputs/$@$(RESET)"

ft_atoi:
	@echo "$(YELLOW)Warning: $(RED)$@ $(RESET)is a function."
	@echo "$(YELLOW)Warning: $(RED)Nothing Compiled !$(RESET)"

.PHONY: first_word fizzbuzz ft_putstr ft_strcpy ft_strlen ft_swap repeat_alpha \
		rev_print rot_13 rotone search_and_replace ulstr alpha_mirror \
		camel_to_snake do_op ft_atoi